# - "group": "joint_angle"
#   "indices": [[0,1,2,3,4,5]]
# - "indices": [[6,7,8,9,10,11]]
# - "indices": [[17, 18, 19, 20, 21, 22, 23, 24]]
# - "indices": [[25, 26, 27, 28, 29, 30, 31, 32]]

# - "group": "tracking"
#   "indices": [[0,1,2,3,4,5]]
# # - "indices": [[6,7,8,9,10,11],[6,7,8,9,10,11]]

- "group": "right_foot_force"
  "indices": [[0,1,2,3,4,5]]

- "group": "left_foot_force"
  "indices": [[0,1,2,3,4,5]]



# - "group": "current"
#   "indices": [[0,1,2,3,4,5]]

# - "group": "imu"
#   "indices": [[0,1,2]]

# - "group": "temperature"
#   "indices": [[0,1,2,3,4,5]]

# - "group": "comp"
#   "indices": [[0,1,2, 3, 4, 5]]

# - "group": "watt"
#   "indices": [[0,1,2,3,4,5]]

# - "group": "ServoState"
#   "indices": [[0,1,2,3,4,5]]

# - "group": "12V"
#   "indices": [[0,1,2,3,4,5]]

# - "group": "80V"
#   "indices": [[0,1,2,3,4,5]]