"joint_angle":
  "log": [['sh_qOut'], ['abc_q'], ['st_q'], ['RobotHardware0_q']]
  "func": ['plot_rad2deg','plot_rad2deg','plot_rad2deg','plot_rad2deg']
  "arg_index": [[0], [0], [0], [0]]

"tracking":
  "log": [['RobotHardware0_q','st_q'], ['RobotHardware0_servoState']]
  "func": ['plot_rh_q_st_q', 'plot_abs_enc']
  "arg_index": [[0,0], [0]]

"right_foot_force":
  "log": [['sh_rfsensorOut'], ['RobotHardware0_rfsensor'], ['rmfo_off_rfsensor']]
  "arg_index": [[0], [0], [0]]

"current":
  "log": [['RobotHardware0_servoState']]
  "func": ['plot_current']
  "arg_index": [[0]]

"imu":
  "log": [['RobotHardware0_gsensor'], ['RobotHardware0_gyrometer']]
  "arg_index": [[0],[0]]

"temperature":
  "log": [['RobotHardware0_servoState'],['RobotHardware0_servoState']]
  "key": ['motor_temp', 'motor_outer_temp']
  "func": ['plot_motor_temp', 'plot_motor_outer_temp']
  "arg_index": [[0],[0]]

"comp":
  "log": [['st_allEEComp']]
  "arg_index": [[0]]

"watt":
  "log": [['RobotHardware0_dq','RobotHardware0_tau']]
  "func": ['plot_watt']
  "arg_index": [[0,0]]

"ServoState":
  "log": [['RobotHardware0_servoState']]
  "func": ['plot_servostate']
  "arg_index": [[0]]

"12V":
  "log": [['RobotHardware0_servoState']]
  "func": ['plot_12V']
  "arg_index": [[0]]

"80V":
  "log": [['RobotHardware0_servoState']]
  "func": ['plot_80V']
  "arg_index": [[0]]
