extend:
  - ../../common_plot.yaml

sh_qOut:
  func: plot_rad2deg
  data:
    - { log: sh_qOut, column: [0-33] }

abc_q:
  func: plot_rad2deg
  data:
    - { log: abc_q, column: [0-33] }

st_q:
  func: plot_rad2deg
  data:
    - { log: st_q, column: [0-33] }

RobotHardware0_q:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_q, column: [0-33] }

rh_st_diff:
  func: plot_rh_q_st_q
  data:
    - { log: RobotHardware0_q, column: [0-33] }
    - { log: st_q, column: [0-33] }

watt:
  func: plot_watt
  data:
    - { log: RobotHardware0_dq, column: [0-33]  }
    - { log: RobotHardware0_tau, column: [0-33] }
