- title: joint_angle(rleg)
  legends:
    - { key: sh_qOut, id: [0-6] }
    - { key: abc_q, id: [0-6] }
    - { key: st_q, id: [0-6] }
    - { key: RobotHardware0_q, id: [0-6] }

- title: joint_angle(lleg)
  legends:
    - { key: sh_qOut, id: [7-13] }
    - { key: abc_q, id: [7-13] }
    - { key: st_q, id: [7-13] }
    - { key: RobotHardware0_q, id: [7-13] }

- title: joint_angle(torso) # chest0, chest1, head0, head1
  legends:
    - { key: sh_qOut, id: [14-17] }
    - { key: abc_q, id: [14-17] }
    - { key: st_q, id: [14-17] }
    - { key: RobotHardware0_q, id: [14-17] }

- title: joint_angle(rarm)
  legends:
    - { key: sh_qOut, id: [18-25] }
    - { key: abc_q, id: [18-25] }
    - { key: st_q, id: [18-25] }
    - { key: RobotHardware0_q, id: [18-25] }

- title: joint_angle(larm)
  legends:
    - { key: sh_qOut, id: [26-33] }
    - { key: abc_q, id: [26-33] }
    - { key: st_q, id: [26-33] }
    - { key: RobotHardware0_q, id: [26-33] }

- title: cog
  legends:
    - { key: abc_cogOut, id: [0-2]}
    - { key: st_originActCog, id: [0-2]}
    - { key: st_originRefCog, id: [0-2]}

- title: tracking
  legends:
    - {key: rh_st_diff, id: [0-5] }

- title: right_foot_force # something bad
  legends:
    - { key: rmfo_off_rfsensor, id: [0-5] }
    - { key: sh_rfsensorOut, id: [0-5] }
    - { key: RobotHardware0_rfsensor, id: [0-5] }


- title: imu_gsensor
  legends:
    - { key: imu_gsensor, id: [0], label: x }
    - { key: imu_gsensor, id: [1], label: y }
    - { key: imu_gsensor, id: [2], label: z }
  newline: False
  downsampling: {ds: 100, auto: False, mode: peak}

- title: imu_gyrometer
  legends:
    - { key: imu_gyrometer, id: [0], label: x }
    - { key: imu_gyrometer, id: [1], label: y }
    - { key: imu_gyrometer, id: [2], label: z }
  downsampling: {ds: 100, auto: False, mode: peak}

- title: comp
  legends:
    - { key: comp, id: [0-5] }

- title: ZMP
  legends:
    - { key: st_zmp, id: [0,1] }

- title: watt
  legends:
    - { key: watt, id: [0-5] }

## - title: ServoState # not work
##   legends:
##     - { key: ServoState, id: [0-5] }

## - title: 12V # not work
##   legends:
##     - { key: 12V, id: [0,1,2,3,4,5] }

## - title: 80V
##   legends:
##     - { key: 80V, id: [0,1,2,3,4,5] }

## - title: current # not work
##   legends:
##     - { key: current, id: [0-5] }

## - title: temperature # not work
##   legends:
##     - { key: motor_temp, id: [0-5] }
##     - { key: motor_outer_temp, id: [0-5] }
